// eslint-disable-next-line react-refresh/only-export-components
const ListingData = [
    {
      id: 1,
      text: "Fancy1",
      desc: "Fancy Product",
      currprice: "$40.00 - $80.00",
      btnname: "View Options",
      listingimg: "Fancyitem1redHipster.jpg",
      sale: false,
      isClick: false,
    },
    {
      id: 2,
      text: "Special1",
      desc: "Special Item",
      discprice: "$20.00",
      btnname: "Add to Cart",
      currprice: "$18.00",
      listingimg: "Specialitem1redloungster.jpg",
      sale: true,
      isClick: false,
    },
    {
      id: 3,
      text: "Sale1",
      desc: "Sale Item",
      btnname: "Add to Cart",
      discprice: "$50.00",
      currprice: "$25.00",
      listingimg: "Saleitem1blacksneaker.jpg",
      sale: true,
      isClick: false,
    },
    {
      id: 4,
      text: "Popular1",
      desc: "Popular Item",
      currprice: "$40.00",
      btnname: "Add to Cart",
      listingimg: "Popularitem1whitehustlers.jpg",
      sale: true,
      isClick: false,
    },
    {
      id: 5,
      text: "Sale2",
      desc: "Sale Item",
      btnname: "Add to Cart",
      discprice: "$50.00",
      currprice: "$25.00",
      listingimg: "Saleitem2blacksneaker.jpg",
      sale: true,
      isClick: false,
    },
    {
      id: 6,
      text: "Fancy2",
      desc: "Fancy Product",
      currprice: "$120.00 - $280.00",
      btnname: "View Options",
      listingimg: "Fancyitem2blackHipster.jpg",
      sale: false,
      isClick: false,
    },
    {
      id: 7,
      text: "Special2",
      desc: "Special Item",
      discprice: "$20.00",
      currprice: "$18.00",
      btnname: "Add to Cart",
      listingimg: "Specialitem2blueloungster.jpg",
      sale: true,
      isClick: false,
    },
    {
      id: 8,
      text: "Popular2",
      desc: "Popular Item",
      currprice: "$40.00",
      btnname: "Add to Cart",
      listingimg: "Popularitem2blacksneaker.jpg",
      sale: true,
      isClick: false,
    },
  ];
  const getImage = () => {
    return ListingData;
  };
  export { getImage };